spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stock_market}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stock_market}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stock_market}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
server.forward-headers-strategy=framework